name: stirling-pdf-casa
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    volumes:
        - /DATA/AppData/stirling-pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
        - /DATA/AppData/stirling-pdf/configs:/configs
        - /DATA/AppData/stirling-pdf/customFiles:/customFiles/
    environment:
        - DOCKER_ENABLE_SECURITY=false
    labels:
        - traefik.enable=true
        - traefik.http.routers.pdf.entryPoints=https
        - traefik.http.routers.pdf.rule=Host(`pdf.cloud-fd.de`)
        - traefik.http.services.pdf.loadbalancer.server.port=8080
        - traefik.http.routers.pdf.middlewares=auth@file
        - homepage.group=Apps & Services
        - homepage.name=Stirling PDF
        - homepage.icon=pdf.png
        - homepage.href=https://pdf.cloud-fd.de
        - homepage.description=Webbased PDF Toolkit & Converter
    networks:
      - dockernet
networks:
  dockernet:
    external: true
x-casaos:
  author: Michael W.
  category: Private
  hostname: pdf2.cloud-fd.de
  icon: https://github.com/louislam/dockge/blob/master/frontend/public/icon-192x192.png
  index: /
  port_map: ""
  scheme: https
  title:
    custom: Stirly-PDF